import mongoose from 'mongoose';

export default [{
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002b8'),
  first_name: 'Tye',
  last_name: 'Haysar',
  email: 'thaysar0@miitbeian.gov.cn',
  password: 'E6HCIX',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002b9'),
  first_name: 'Nobie',
  last_name: 'Sciusscietto',
  email: 'nsciusscietto1@booking.com',
  password: '9WU3XhyA',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002ba'),
  first_name: 'Katy',
  last_name: 'Toffts',
  email: 'ktoffts2@gravatar.com',
  password: 'Rrq2t0R6',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002bb'),
  first_name: 'Josey',
  last_name: 'Styan',
  email: 'jstyan3@nps.gov',
  password: 'UG1WE9GiP',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002bc'),
  first_name: 'Dominik',
  last_name: 'Cribbott',
  email: 'dcribbott4@tamu.edu',
  password: 'pNf5NO2aKEL',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002bd'),
  first_name: 'Minetta',
  last_name: 'Reeds',
  email: 'mreeds5@foxnews.com',
  password: 'OXx3l9',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002be'),
  first_name: 'Josy',
  last_name: 'Gisbourn',
  email: 'jgisbourn6@jalbum.net',
  password: 'I6BBorDD3N1',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002bf'),
  first_name: 'Antonina',
  last_name: 'Westrey',
  email: 'awestrey7@xrea.com',
  password: 'PypVekaijw',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002c0'),
  first_name: 'Annette',
  last_name: 'Antrag',
  email: 'aantrag8@china.com.cn',
  password: 'gJMLJoSu0d9m',
}, {
  _id: mongoose.Types.ObjectId('635437ebfc13ae2db70002c1'),
  first_name: 'Natala',
  last_name: 'Howgill',
  email: 'nhowgill9@gizmodo.com',
  password: 'vR8GVpdyY',
}];
